
let rules = [`
"CANCELLATIONS
ANY TIME
CANCELLATIONS PERMITTED.
CANCELLATIONS
ANY TIME
TICKET IS NON-REFUNDABLE.
CHANGES
ANY TIME
CHANGES PERMITTED FOR REISSUE/REVALIDATION.
CHANGES
ANY TIME
CHANGES PERMITTED.
NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.
1ST CHANGE PERMITTED WITH FREE OF CHARGE UP TO
30 DAYS BEFORE DEPARTURE.
-------------------------------------------------
IF CHANGES ARE MADE WITHIN 30 DAYS BEFORE
DEPARTURE A FEE OF USD 200.00 SHOULD BE APPLIED.
--------------------------------------------------
IN CASE OF NO-SHOW - CHANGE IS NOT PERMITTED.
`];


