
let rules = [`
"ORIGINATING AREA 1 -
CANCELLATIONS
ANY TIME
CHARGE USD 200.00 FOR REFUND.
WAIVED FOR SCHEDULE CHANGE/ILLNESS OR DEATH OF
PASSENGER OR FAMILY MEMBER.
NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.
-FAMILY MEMBER MUST BE FIRST DEGREE RELATIVE.
WAIVER ALSO APPLIES FOR TRAVELING COMPANION.
ILLNESS/DEATH WAIVERS MUST BE SUBSTANTIATED BY A
VALID MEDICAL/DEATH CERTIFICATE.
CHANGES
ANY TIME
CHARGE USD 170.00.
WAIVED FOR SCHEDULE CHANGE/ILLNESS OR DEATH OF
PASSENGER OR FAMILY MEMBER.
NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.
-FAMILY MEMBER MUST BE FIRST DEGREE RELATIVE-
WAIVER ALSO APPLIES FOR TRAVELING COMPANION
ILLNESS/DEATH WAIVERS MUST BE SUBSTANTIATED BY A
VALID MEDICAL/DEATH CERTIFICATE.
--------------------------------
NOTE-
-TICKETS MUST BE REISSUED WHEN ANY VOLUNTARY
CHANGE IS MADE.
-SEE /CHILD/INFANT DISCOUNT/ IN FARE RULE TO
DETERMINE IF APPLICABLE.
ORIGINATING AREA 2 -
CANCELLATIONS
ANY TIME
CHARGE EUR 150.00 FOR REFUND.
WAIVED FOR SCHEDULE CHANGE/DEATH OF PASSENGER
OR FAMILY MEMBER.
NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.
-FAMILY MEMBER MUST BE FIRST DEGREE RELATIVE.-
1. RESERVATION CANCELLED RETAINS TICKET VALUE/LESS
APPLICABLE CHANGE FEE AND ANY DIFFERENCE IN FARE
INDICATED IN CHANGE PARAGRAPH UP TO ONE YEAR FROM
THE ORIGINAL DATE OF TICKET ISSUE.
2.ILLNESS/DEATH WAIVERS MUST BE SUBSTANTIATED BY A
VALID MEDICAL/DEATH CERTIFICATE.
NOTE-
-SEE /CHILD/INFANT DISCOUNT/IN FARE RULE TO
DETERMINE IF APPLICABLE.
ANY TIME
CHARGE EUR 80.00 FOR NO-SHOW.
CHANGES
ANY TIME
CHARGE EUR 120.00.
WAIVED FOR SCHEDULE CHANGE/ILLNESS OR DEATH OF
PASSENGER OR FAMILY MEMBER.
NOTE - TEXT BELOW NOT VALIDATED FOR AUTOPRICING.
-FAMILY MEMBER MUST BE FIRST DEGREE RELATIVE-
WAIVER ALSO APPLIES FOR TRAVELING COMPANION
ILLNESS/DEATH WAIVERS MUST BE SUBSTANTIATED BY A
VALID MEDICAL/DEATH CERTIFICATE.
--------------------------------
NOTE-
-TICKETS MUST BE REISSUED WHEN ANY VOLUNTARY
CHANGE IS MADE.
-SEE /CHILD/INFANT DISCOUNT/ IN FARE RULE TO
DETERMINE IF APPLICABLE."

`];


